name: Release 
on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: macos-latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - name: Install Taskfile
              uses: arduino/setup-task@v1
              with:
                repo-token: ${{ env.GH_TOKEN }}
            - name: Release
              run: task release
